auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /etc/loki
  storage:
    filesystem:
      chunks_directory: /etc/loki/chunks
      rules_directory: /etc/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# schema_config:
#   configs:
#     - from: 2020-10-24
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v11
#       index:
#         prefix: index_
#         period: 24h

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

# will fix a lot of "context canceled" log messages
# https://github.com/grafana/loki/pull/5077/files#diff-025adfc5a8f641b9f5a1869996e3297b6c17f13933f52354cd9b375548ad7970R399
query_range:
  parallelise_shardable_queries: false
  align_queries_with_step: true
  cache_index_stats_results: true
  cache_results: true
  cache_volume_results: true
  cache_series_results: true
  series_results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        consistent_hash: true
        addresses: "dns+localhost:11211"
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m
  index_stats_results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        consistent_hash: true
        addresses: "dns+localhost:11211"
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m
  max_retries: 5
  results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        consistent_hash: true
        addresses: "dns+localhost:11211"
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m
  volume_results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        consistent_hash: true
        addresses: "dns+localhost:11211"
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m

ruler:
  alertmanager_url: http://localhost:9093
# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
analytics:
  reporting_enabled: false
